version: "3.8"

services:
  api_store:
    build:
      context: .
      dockerfile: docker/Dockerfile-api
    user: "node"
    working_dir: /usr/src/api
    environment:
      - NODE_ENV=development
      - SERVICE_NAME=store
    volumes:
      - ./api:/usr/src/api
    ports:
      - "3000:3000"
    tty: true
    depends_on:
      - db
      - memcache
  api_panel_seller:
    build:
      context: .
      dockerfile: docker/Dockerfile-api
    user: "node"
    working_dir: /usr/src/api
    environment:
      - NODE_ENV=development
      - SERVICE_NAME=panel_seller
    volumes:
      - ./api:/usr/src/api
    ports:
      - "3001:3001"
    tty: true
    depends_on:
      - db
      - memcache
  api_panel_admin:
    build:
      context: .
      dockerfile: docker/Dockerfile-api
    user: "node"
    working_dir: /usr/src/api
    environment:
      - NODE_ENV=development
      - SERVICE_NAME=panel_admin
    volumes:
      - ./api:/usr/src/api
    ports:
      - "3002:3002"
    tty: true
    depends_on:
      - db
      - memcache
  db:
    image: 'postgres:latest'
    container_name: postgres.dev.store
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=store
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
  memcache:
    image: 'memcached:latest'
    container_name: memcache.dev.store
    ports:
      - "11211:11211"
